name: Test GitHub Secret

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Test Secret
        run: |
          # 不要直接打印 secret，这仅用于测试确认 secret 已设置
          if [ -n "${{ secrets.API_KEY }}" ]; then
            echo "Secret is set and available"
            echo "Secret length: $(echo '${{ secrets.API_KEY }}' | wc -c)"
          else
            echo "Secret is not set"
          fi
        
      # 示例：使用 secret 调用脚本
      - name: Use Secret in Script
        run: |
          echo "调用外部 API..."
          # 这里是一个示例，实际使用时你可能有自己的脚本
          # curl -H "Authorization: Bearer ${{ secrets.API_KEY }}" https://api.example.com/data
